# Generated by Django 5.2.7 on 2025-11-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_image_alter_course_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to='courses/'),
        ),
    ]
