# Generated by Django 5.2.7 on 2025-11-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicitem',
            name='link',
        ),
        migrations.AddField(
            model_name='academicitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='academics/'),
        ),
    ]
