# Generated by Django 5.2.7 on 2025-11-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('Chairman', 'Chairman'), ('Vice Chairman', 'Vice Chairman'), ('Director General', 'Director General'), ('Assistant Director', 'Assistant Director'), ('Registrar', 'Registrar'), ('Head of Department', 'Head of Department'), ('Lecturer', 'Lecturer'), ('Senior Lecturer', 'Senior Lecturer'), ('Instructor', 'Instructor'), ('Staff', 'Staff')], default='Staff', max_length=50),
        ),
    ]
